### ISSUE TITLE
 Call to undefined function Tepuilabs\PaymentProcessors\config() 

### ISSUE THREAD

**Issue by blackzig** [TepuiLABS/payment-processors#4]
public function payments(): void {
        $head = $this->seo->render(
                CONF_SITE_NAME . " - Pagamentos",
                CONF_SITE_DESC,
                url("/pagamentos"),
                theme(CONF_SOCIAL_SHARED_POST),
        );

        $params = [
            'base_uri' => 'https://api.mercadopago.com',
            'key' => CONF_MERCADOPAGO_PUBLIC_KEY,
            'secret' => CONF_MERCADOPAGO_CLIENT_SECRET,
            'base_currency' => 'BRL',
        ];

        $mercadopago = PaymentProcessors::resolveService('mercadopago', $params);

        echo $this->view->render("buy/payment", [
            "head" => $head,
            "mercadopago" => $mercadopago
        ]);
    }

Resultado:

Fatal error: Uncaught Error: Call to undefined function Tepuilabs\PaymentProcessors\config() in C:\xampp\htdocs\saudavelmente\vendor\tepuilabs\payment-processors\src\PaymentProcessors.php:20 Stack trace: #0 C:\xampp\htdocs\saudavelmente\source\App\MercadoPago.php(29): Tepuilabs\PaymentProcessors\PaymentProcessors::resolveService('mercadopago', Array) #1 C:\xampp\htdocs\saudavelmente\vendor\coffeecode\router\src\Dispatch.php(143): Source\App\MercadoPago->payments(Array) #2 C:\xampp\htdocs\saudavelmente\vendor\coffeecode\router\src\Dispatch.php(123): CoffeeCode\Router\Dispatch->execute() #3 C:\xampp\htdocs\saudavelmente\index.php(191): CoffeeCode\Router\Dispatch->dispatch() #4 {main} thrown in C:\xampp\htdocs\saudavelmente\vendor\tepuilabs\payment-processors\src\PaymentProcessors.php on line 20

**Comment by abr4xas** [comment]
@blackzig Sorry for being late in my answer, can you create a repo where I can reproduce this error?
